"""add_performance_indexes

Revision ID: 812c8597a3cf
Revises: 5b6c2d981b4f
Create Date: 2026-06-01 19:41:37.024083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '812c8597a3cf'
down_revision: Union[str, Sequence[str], None] = '5b6c2d981b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_conversation_orphaned_archived', 'conversations', ['is_orphaned', 'is_archived'], unique=False)
    op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_message_created', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_index('idx_conversation_orphaned_archived', table_name='conversations')
    # ### end Alembic commands ###
